// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LoggerMessageTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "LoggerMessageTools.a14103ce-b5fc-4479-8ae5-68efc969fcf5";
        public const string Name = "LoggerMessageTools";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Андрей Клебан";
        public const string Tags = "";
    }
}
